### ISSUE TITLE
Error on build docs

### ISSUE THREAD

**Issue by tbille** [canonical-web-and-design/docs.ubuntu.com#233]
When running `./build-docs.sh`

```
Traceback (most recent call last):
  File "/home/toto/.pyenv/versions/docs.ubuntu.com/bin/documentation-builder", line 8, in <module>
    from ubuntudesign.documentation_builder import cli
  File "/home/toto/.pyenv/versions/3.6.5/envs/docs.ubuntu.com/lib/python3.6/site-packages/ubuntudesign/documentation_builder/cli.py", line 7, in <module>
    from .builder import Builder
  File "/home/toto/.pyenv/versions/3.6.5/envs/docs.ubuntu.com/lib/python3.6/site-packages/ubuntudesign/documentation_builder/builder.py", line 19, in <module>
    from .operations import (
  File "/home/toto/.pyenv/versions/3.6.5/envs/docs.ubuntu.com/lib/python3.6/site-packages/ubuntudesign/documentation_builder/operations.py", line 13, in <module>
    from git import Repo
  File "/home/toto/.pyenv/versions/3.6.5/envs/docs.ubuntu.com/lib/python3.6/site-packages/git/__init__.py", line 38, in <module>
    from git.exc import *                       # @NoMove @IgnorePep8
  File "/home/toto/.pyenv/versions/3.6.5/envs/docs.ubuntu.com/lib/python3.6/site-packages/git/exc.py", line 9, in <module>
    from git.compat import UnicodeMixin, safe_decode, string_types
  File "/home/toto/.pyenv/versions/3.6.5/envs/docs.ubuntu.com/lib/python3.6/site-packages/git/compat.py", line 16, in <module>
    from gitdb.utils.compat import (
ModuleNotFoundError: No module named 'gitdb.utils.compat'
```

**Comment by Harmon758** [comment]
See https://github.com/gitpython-developers/GitPython/issues/983.
